{
    "base_url": "http://stable.release.core-os.net/amd64-usr",
    "target_dir": "bootstrap/coreos/stable",
    "artifacts": [
        "coreos_production_image.bin.bz2"
    ],
    "versions": [
        "717.3.0",
        "723.3.0"
    ]
}
